export const FETCH_BRIDGE_INFO = 'FETCH_BRIDGE_INFO'
export const FETCH_LOGIN_STATUS = 'FETCH_LOGIN_STATUS'
export const LOADING_STATUS = 'SET_LOADING_STATUS'
export const FETCH_TOPIC_BOARDS = 'FETCH_TOPIC_BOARDS'
export const NAVBAR_SELECT = 'NAVBAR_SELECT'
export const FETCH_BBS_HOME_DATA = 'FETCH_BBS_HOME_DATA' // 获取社区首页数据

// 个人中心部分
export const CHANGE_UNREAD_STATUS = 'CHANGE_UNREAD_STATUS' // 消息未读状态更改
export const FETCH_BBS_USER_INFO = 'FETCH_BBS_USER_INFO' // 获取社区用户信息
